# Where all the include files are:
INCS = /I.
CC = cl /nologo
CFLAGS = /c /O2 /Oi /Ot /GS /D_WIN32

OBJS = egif_lib.obj dgif_lib.obj gifalloc.obj gif_font.obj gif_hash.obj \
	gif_err.obj quantize.obj

.c.obj:
	$(CC) $(INCS) $(CFLAGS) $<

all: $(OBJS)
	lib /out:libgif.lib $(OBJS)

clean:
	del /Q *.obj
	del /Q *.lib
